<?php

/**
 * @file
 * Contains example_csv_update.module
 */

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;
use Drupal\migrate\MigrateSkipRowException;

/**
 * Implements hook_migrate_prepare_row().
 */
function example_csv_update_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  if ($migration->id() == 'example_csv_content_type_migration' || $migration->id() == 'example_csv_term_migration') {
    $text_fields = ['title', 'body', 'misc', 'term_name'];

    $language = $row->getSourceProperty('content_langcode');

    if (!$language) {
      throw new MigrateSkipRowException('No langcode found in source.', TRUE);
    } elseif ($language === "en") {
      throw new MigrateSkipRowException('English content, no translation needed.', FALSE);
    }

    foreach ($text_fields as $field) {
      if (!$row->hasSourceProperty($field)) {
        throw new MigrateSkipRowException('Missing translatable text field.', TRUE);
      }
      // encode each field to avoid SQL format errors.
      $row->setSourceProperty($field, utf8_encode($row->getSourceProperty($field)));
    }
  }
}
